# Generated by Django 4.2.28 on 2026-04-22 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('pk_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pk_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField()),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('pk_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_producto', models.IntegerField()),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='Productos.productos')),
                ('fk_venta', models.ForeignKey(db_column='fk_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='Ventas.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('pk_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_producto', models.IntegerField()),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
                ('fk_pedido', models.ForeignKey(db_column='fk_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='Ventas.pedidos')),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='Productos.productos')),
            ],
            options={
                'db_table': 'detalle_pedidos',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('pk_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='Productos.productos')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
    ]
