# Generated by Django 4.2.28 on 2026-06-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('pk_venta', models.AutoField(primary_key=True, serialize=False)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('cantidad_producto', models.IntegerField(null=True)),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Productos.productos')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='fk_estado',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='fk_usuario',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
