# Generated by Django 4.2.28 on 2026-06-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ventas', '0002_venta_remove_ventas_fk_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
