# Generated by Django 4.2.28 on 2026-06-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_vista_icono'),
        ('Ventas', '0003_venta_fk_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fk_estado',
            field=models.ForeignKey(db_column='fk_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado'),
        ),
    ]
