# Generated by Django 4.2.28 on 2026-06-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ventas', '0004_venta_fk_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprador',
            field=models.ForeignKey(db_column='fk_comprador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
