# Generated by Django 4.2.28 on 2026-04-22 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('pk_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(null=True)),
                ('stock', models.IntegerField(default=0)),
                ('codigo_producto', models.CharField(max_length=50, unique=True)),
                ('muestra_nombre', models.BooleanField(default=True)),
                ('muestra_telefono', models.BooleanField(default=False)),
                ('muestra_correo', models.BooleanField(default=False)),
                ('ruta_imagen', models.CharField(max_length=255, null=True)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
