# Generated by Django 4.2.28 on 2026-04-21 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('pk_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('pk_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('pk_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=500)),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('correo', models.CharField(max_length=100, null=True, unique=True)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
                ('fk_rol', models.ForeignKey(db_column='fk_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('pk_vista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=200, unique=True)),
                ('visible_en_navbar', models.BooleanField(default=True)),
                ('fk_estado', models.ForeignKey(db_column='fk_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.estado')),
            ],
            options={
                'db_table': 'vista',
            },
        ),
        migrations.CreateModel(
            name='Login_log',
            fields=[
                ('pk_login_log', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('login', models.CharField(max_length=5, null=True)),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_log',
            },
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('pk_permiso_rol', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_acceso', models.BooleanField(default=True)),
                ('fk_rol', models.ForeignKey(db_column='fk_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.rol')),
                ('fk_vista', models.ForeignKey(db_column='fk_vista', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.vista')),
            ],
            options={
                'db_table': 'permiso_rol',
                'unique_together': {('fk_rol', 'fk_vista')},
            },
        ),
    ]
