# Generated by Django 4.2.28 on 2026-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vista',
            name='icono',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
